export const snake_head_right = new Image();
snake_head_right.src = "/img/snake-head-right.png";
export const snake_head_left = new Image();
snake_head_left.src = "/img/snake-head-left.png";
export const snake_head_up = new Image();
snake_head_up.src = "/img/snake-head-up.png";
export const snake_head_down = new Image();
snake_head_down.src = "/img/snake-head-down.png";
export const snake_down_right = new Image();
snake_down_right.src = "/img/snake-down-right.png";
export const snake_down_left = new Image();
snake_down_left.src = "/img/snake-down-left.png";
export const snake_up_right = new Image();
snake_up_right.src = "/img/snake-up-right.png";
export const snake_up_left = new Image();
snake_up_left.src = "/img/snake-up-left.png";
export const snake_straight = new Image();
snake_straight.src = "/img/snake-straight.png";
export const snake_up_down = new Image();
snake_up_down.src = "/img/snake-up-down.png";
export const apple = new Image();
apple.src = "/img/apple.png";
export const ground1 = new Image()
ground1.src = "/img/ground1.png"
export const ground2 = new Image()
ground2.src = "/img/ground2.png"
export const snake_tail_right = new Image();
snake_tail_right.src = "/img/snake-tail-right.png";
export const snake_tail_left = new Image();
snake_tail_left.src = "/img/snake-tail-left.png";
export const snake_tail_up = new Image();
snake_tail_up.src = "/img/snake-tail-up.png";
export const snake_tail_down = new Image();
snake_tail_down.src = "/img/snake-tail-bottom.png";